# Generated by Django 5.1 on 2024-11-26 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Request',
        ),
    ]
