# Generated by Django 5.1 on 2024-11-26 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_comment_status_alter_comment_post_alter_comment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='take_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.topic'),
        ),
    ]
