# Generated by Django 5.1 on 2024-11-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_profile_phone_alter_profile_about_alter_section_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='recently_viewed',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
