# Generated by Django 5.1 on 2024-12-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_views_post_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notification',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
